// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
/*
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],

export default sidebars;
*/

const sidebars = {

  rgoneSidebar: [
    'what-is-rgone',
    {
      type: 'category',
      label: 'For all rgOne Apps',
      items: [
        'getting-help',   
        'logging-on-to-rgone', 
        'logging-off-of-rgone',
        'navigating-rgone-ui',
        {
          type: 'category',
          label: 'Widget dashboard guide',
          items: [
            'widget-dashboard-guide-overview',
            'navigating-to-widget-dashboard',
            'adding-a-widget',
            'configuring-a-widget',
            'refreshing-a-widget',
            'moving-widgets-around-the-dashboard',
            'deleting-a-widget',
            'common-widget-configuration-settings',
            {
              type: 'category',
              label: 'Widgets',
              items: [
                'activity-widget',
                'channel-overview-widget',
                'chart-widget',
                'data-callout-widget',
                'simple-title-widget',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'User management',
          items: [
            'user-roles',
            'user-types', 
            'adding-user-roles-and-user-accounts',
            'adding-a-user-role',
            'adding-a-user-account',
            'adding-app-admin-and-system-admin-accounts',
            'adding-an-app-admin-account',
            'adding-a-system-admin-account',
          ],
        },
        'accessing-rgone-api-docs',
        {
          type: 'category',
          label: 'Deploying and configuring rgOne apps',
          items: [
            'deploying-rgone-on-single-linux-vm',
            'deploying-aml-on-kubernetes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Automated Machine Learning',
      items: [
        'why-use-machine-learning',
        'how-machine-learning-works',
        {
          type: 'category',
          label: 'AML User Interface',
          items: [
            'project-manager-page',
            {
              type: 'category',
              label: 'Data Manager Page',
              items: [
                'data-manager-page',
                'file-manager-tab',
                'connections-tab',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Creating a new project',
          items: [
            'models-vs-solutions',
            'what-is-a-project',
            'steps-for-building-a-project',
            {
              type: 'category',
              label: 'Choosing a template or model',
              items: [
                'templates-vs-models',
                'project-templates',
                'data-models',
                'choosing-a-template-or-model',
              ],
            },
            {
              type: 'category',
              label: 'Project configuration page',
              items: [
                'project-configuration-page',
                'project-configuration-page-sections',
                'editing-a-section',
                'section-status-light',
                'project-validation',
              ],
            },
            'draft-status',
            'brief-aside-data-file-notation-and-project-features',
            {
              type: 'category',
              label: 'Adding data files',
              items: [
                'data-set-types-used-by-aml',
                'file-upload-methods',
                'uploading-and-choosing-a-data-file-via-the-file-manager',
                {
                  type: 'category',
                  label: 'Uploading and choosing a data file via a Data Connection',
                  items: [
                    'uploading-and-choosing-a-data-file-via-a-data-connection',
                    'creating-a-data-connection',
                    'attaching-a-file-uploaded-by-a-data-connection-to-a-project',
                    'automating-file-uploads-via-a-data-connection',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Choosing features',
              items: [
                'choosing-input-and-output-features',
                'choosing-output-features',
                'choosing-input-features-for-most-model-types',
                'choosing-input-features-for-pr-models',
              ],
            },
            'a-reminder-about-modifying-project-sections',
          ],
        },
        {
          type: 'category',
          label: 'Training a project',
          items: [
            'training-a-project',
            'training-a-cloned-project',
            'things-you-can-do-with-a-trained-project',
          ],
        },
        'analyzing-a-projects-training-results',
        'publishing-a-solution',
        {
          type: 'category',
          label: 'Model examples',
          items: [
            'model-example-classification',
            'model-example-clustering',
            'model-example-regression',
            'model-example-pr',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'category',
              label: 'Features',
              items: [
                'features-overview',
                'general-thoughts-on-project-data-files-and-features',
                'number-of-input-features-vs-number-of-data-samples',
              ],
            },
            {
              type: 'category',
              label: 'Model training and testing',
              items: [
                'model-training-and-testing-overview',
                'training-vs-testing-data',
                'choosing-holdout-data',
                'how-many-records-to-use-in-training-and-testing',
                'how-parents-and-children-are-chosen-for-each-generation',
                {
                  type: 'category',
                  label: 'How a solution fitness score is calculated',
                  items: [
                    'how-a-solution-fitness-score-is-calculated',
                    'sample',
                    'fitness-portion',
                    'solution-fitness-score-example',
                  ],
                },
                'how-a-model-rank-value-is-calculated',
                {
                  type: 'category',
                  label: 'Training algorithms',
                  items: [
                    'training-algorithms',
                    'linear-least-squares',
                    'partial-least-squares',
                    'neural-networks',
                    'clustering-algorithms',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Project actions',
              items: [
                'project-actions',
                'stop-training',
                'edit-project',
                "resume-training",
                "clone-project",
                "view-project",
                {
                  type: 'category',
                  label: 'Fitness report',
                  items: [
                    'fitness-report',
                    'graph-options',
                  ],
                },
                'archive-project',
              ],
            },
            {
              type: 'category',
              label: 'Solutions page',
              items: [
                'solutions-page',
                'report-page',
                {
                  type: 'category',
                  label: 'Solution actions',
                  items: [
                    'solution-actions',
                    'sample-using-holdout-data',
                    'sample-prediction',
                    'download-data',
                    'publish',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Project settings and UI',
              items: [
                'project-settings-and-ui-overview',
                {
                  type: 'category',
                  label: 'All project types',
                  items: [
                    {
                      type: 'category',
                      label: 'Project configuration page settings',
                      items: [
                        'project-configuration-page-settings',
                        'training-options',
                        "data-options",
                        "optimizer",
                        "run-settings",
                        "automation-run-settings",
                      ],
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Classification projects',
                  items: [
                    'the-test-data-set',
                    'creating-a-predictive-model',
                    'feature-actions',
                  ],
                },
                {
                  type: 'category',
                  label: 'Clustering projects',
                  items: [
                    'what-does-the-clustering-model-do',
                    'thoughts-on-cluster-size',
                    'clustering-model-algorithms-reference-publications',
                    {
                      type: 'category',
                      label: 'Clustering measure functions',
                      items: [
                        'semi-supervised-clustering-measure-functions',
                        'unsupervised-clustering-measure functions',
                        'clustering-measure-functions-reference-publications',
                      ],
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Regression projects',
                  items: [
                    'about-the-regression-model',
                  ],
                },
                {
                  type: 'category',
                  label: 'Product Recommender projects',
                  items: [
                    'about-the-product-recommender-model',
                  ],
                },
              ],
            },
            

          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Campaign Creation',
      items: [
        'coming-soon',
      ],
    },
    {
      type: 'category',
      label: 'Customer View',
      items: [
        'scv-configuration',
      ],
    },
  ],
};

export default sidebars;